### Get all
GET http://localhost:3000/clays 

### Get clay by id
GET http://localhost:3000/clays/1



### Add a new clay
POST http://localhost:3000/clays HTTP/1.1
content-type: application/json

{
    "name": "hawaiian blue",
    "notes": "a blue groggy clay"
}

### Delete clay
DELETE http://localhost:3000/clays/1